### ISSUE TITLE
Revised architecture diagram

### ISSUE THREAD

**Issue by rBergCode** [HikeMate/hikeMateApp#102]
In addition to completing the [architecture diagram](https://excalidraw.com/#json=CmTW2w9uCvZiB0Ba-RMEo,4HCBowSuVRJMrDFuGSFXxQ) with the further developments of the app, one needs to address the feedback received in milestone 1 :

> The diagram is complete, but it’s a bit difficult to read. It would be helpful to space things out more and regroup the different layers for better clarity. Additionally, the domain layer could be further developed to provide more detail.

**Definition of Done**
- [x] Add new elements that were introduced in further development of the app since M1
- [x] Space things out
- [x] Regroup the elements of each layer for better clarity
- [x] Develop the domain layer further to provide more detail

**Comment by rBergCode** [comment]
Here is the link:
https://excalidraw.com/#json=pV6tDKOM8ABPawsY5ORYG,I8pEamva2KnkwAkdbqD_OQ

**Comment by mchac15** [comment]
![Uploading Untitled-2024-11-15-0005.png…]()

**Comment by mchac15** [comment]
![image](https://github.com/user-attachments/assets/ae4ead2b-add1-45c6-bc10-e2770bf73dd0)
