### ISSUE TITLE
Implement the hike details screen

### ISSUE THREAD

**Issue by davidholzwarth** [HikeMate/hikeMateApp#111]
This task requires the Figma of the Hike Details screen to be done and approved by the team.

Implement a new screen that represents the details of one particular hike. That screen will contain significantly more information than the others, refer to the Figma to see what information should be displayed and how.

**Definition of Done**

- [x] The hike details screen is implemented according to the Figma design
- [x] Data that is already available through the `HikeRoute` type are displayed
- [x] Data that are not yet available through the `HikeRoute` type have dummy placeholders that make sense for a demo
- [x] The hike's elevation profile graph is not displayed, instead a gray rectangle placeholder will do for now
- [x] Clicking on a hike in the list on the map screen opens the details screen of this hike
- [x] Clicking on a hike on the map (on its drawn line) opens the details screen of this hike
- [ ] ~~Clicking on a hike in the list in the saved hikes screen opens the details screen of that hike~~

**Explicitly not part of the Definition of Done**

- Don't implement additional view models and repositories to gather missing information (such as restrooms locations, ...), this would be out of this task's scope.
- Another task exists to create a component such as `HikeElevationGraph` to display the graph of the hike's elevation profile. Do not implement it as part of this task.
-  To avoid dependencies, merging `HikeElevationGraph` with the Hike Details screen has been made another task, hence use a placeholder gray rectangle or something instead of the graph, another PR will add the graph to the screen.

**Tips**

When linking the `MapScreen` and the `SavedHikesScreen` to the details one, search for `Hike details not implemented yet`. You should find two results in the map screen (one for the click of a hike list item, and one for a hike line clicked on the map), and one in saved hikes screen (when a hike is clicked in the list).

Replace those events with a navigation action to the details screen for that particular hike.

**Comment by MaelImhof** [comment]
> Clicking on a hike in the list in the saved hikes screen opens the details screen of that hike

This has been moved to another task.

**Comment by davidholzwarth** [comment]
Finished in #115
