### ISSUE TITLE
Refactor the MapScreen

### ISSUE THREAD

**Issue by mchac15** [HikeMate/hikeMateApp#137]
The `MapScreen` has become too complicated and it needs some refractoring.

- [ ] Refractor the MapScreen into separate chunks of code.

**Comment by MaelImhof** [comment]
> Solve the "bug" in which when a user tries to center the map around the user the animation blocks the map from moving. This should be handled like in Google Maps where the user can cancel this animation and the map won't be centered at the end if the user moves the map.

This is not refactoring, this is a bug fix (or feature depending on how you see it), I think it should be another separate task.

Also, I would add refactoring the location logic, because it needs to be moved to a view model or something, be more structured and maintanable.
