### ISSUE TITLE
Implement map screen

### ISSUE THREAD

**Issue by MaelImhof** [HikeMate/hikeMateApp#28]
_**Note:** This Task was planned to be finished in S1, however we are moving it to S2 since there was not enough time to finish it._

 The map should come from openstreetmap and not GoogleMap.
The list of routes can be hardcoded at this point

**Definition of done**
- [x] A map is displayed as the main component of the app
- [x] The map is from OpenStreetMap, as opposed to Google Maps for example
- [x] The user can interact with the map (drag and zoom) to display different locations
- [x] A list of hiking routes is displayed, at the bottom of the screen
- [x] The list of hiking routes can be expanded to the top to fill the screen, or be kept as a smaller part of the screen to display the map on the rest

**Comment by rBergCode** [comment]
Closed by #36
