### ISSUE TITLE
Merge navigation with sign-in feature and map

### ISSUE THREAD

**Issue by mchac15** [HikeMate/hikeMateApp#32]
_**Note:** This Task was planned to be finished in S1, however we are moving it to S2 since deliverables that it depends one could not be finished in S1._

Requires both navigation setup and sign in flow in order to complete. At the end of this task the app should launch into the log in screen and after logging in proceed to the next scree, so that we can create a working demo out of the app

Done criteria

- [x] Opening the app shows the sign in screen
- [x] A successful login opens the Map screen as per the Figma Wireframe

**Comment by mchac15** [comment]
Waiting for #28 and #24 to be done but it is basically finished.

**Comment by MaelImhof** [comment]
About #28, a menu button is already included in the map screen. You can either use it or remove it and use your own. It's defined with the following lines, starting line 113 of `MapScreen.kt` (or around this, depending on changes for the PR merge, but should be around lines 110-120).

```kotlin
// Burger menu button in the top left corner of the screen
    IconButton(
        onClick = {
          // TODO : Adapt the map screen to navigation
          Toast.makeText(context, "Menu not implemented yet", Toast.LENGTH_SHORT).show()
        },
        modifier =
            Modifier.padding(16.dp)
                .align(Alignment.TopStart)
                // Clip needs to be before background
                .clip(RoundedCornerShape(8.dp))
                .background(MaterialTheme.colorScheme.surface)
                .testTag(MapScreen.TEST_TAG_MENU_BUTTON)) {
          Icon(
              Icons.Default.Menu,
              contentDescription =
                  context.getString(R.string.map_screen_menu_button_content_description),
              tint = MaterialTheme.colorScheme.onSurface)
        }
```
